version: "3.7"
services:
  loki:
    image: grafana/loki
    container_name: loki
    logging:
      options:
        max-size: "10k"
        max-file: "5"
    volumes:
      - ./loki_config.yml:/etc/loki/config.yml
    ports:
      - 3100:3100
    command: ["-config.file=/etc/loki/config.yml"]
