auth_enabled: true

server:
  http_listen_port: 3100

common:
  path_prefix: /tmp/loki
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

# https://github.com/grafana/loki/issues/4613#issuecomment-1045993131  
query_scheduler:
  max_outstanding_requests_per_tenant: 2048
query_range:
  parallelise_shardable_queries: false
  split_queries_by_interval: 0

# https://github.com/grafana/loki/issues/4509
limits_config:
  max_query_length: 0

querier:
  engine:
    max_look_back_period: 5m